development:
  adapter: mysql
  database: tracks
  # set this if you are storing utf8 in your mysql database to handle strings
  # like "Réné".Not needed for sqlite. For PostgreSQL use encoding: unicode
  # encoding: utf8
  host: localhost
  username: root
  password: 123456

test: &TEST
    adapter: sqlite3
    database: ":memory:"

production:
  adapter: mysql
  database: th88352_2doo
  # set this if you are storing utf8 in your mysql database to handle strings
  # like "Réné".Not needed for sqlite. For PostgreSQL use encoding: unicode
  # encoding: utf8
  host: localhost
  username: th88352_admin
  password: 2011cream682

cucumber:
  <<: *TEST

selenium:
  <<: *TEST
